"""s13_loopgroup.py -- the group H generated by the rows of a random loop (reduced Latin square).

For a Latin square L with rows r_i (as permutations column -> symbol), H(L) = < r_1^{-1} r_i : i > is the left
multiplication group of the loop isotope obtained by normalising the first row to the identity (and then any row
permutation).  Classify H as S_n / A_n / other, and for 'other' whether it is primitive, imprimitive (with a block
system) or intransitive (impossible for loops; sanity check).

usage:  python3 s13_loopgroup.py exact n            # enumerate all reduced squares (n <= 6)
        ./jm n nsamp thin seed | python3 s13_loopgroup.py sample n
"""
import sys
from math import factorial
from sympy.combinatorics import Permutation, PermutationGroup
from s8_real_bias import read_squares


def row_group(L):
    n = len(L)
    r1 = Permutation(L[0])
    gens = [r1 ** -1 * Permutation(L[i]) for i in range(1, n)]
    return PermutationGroup(gens)


def classify(L):
    n = len(L)
    H = row_group(L)
    o = H.order()
    if o == factorial(n):
        return 'S_n'
    if o == factorial(n) // 2:
        return 'A_n'
    if not H.is_transitive():
        return 'intransitive'
    if H.is_primitive():
        return f'primitive order {o}'
    blocks = H.minimal_block([0, 1])
    # find a nontrivial block system via minimal_block over pairs
    for j in range(1, n):
        b = H.minimal_block([0, j])
        size = b.count(b[0])
        if 1 < size < n:
            return f'imprimitive blocks {size} order {o}'
    return f'imprimitive order {o}'


def reduced_squares(n):
    """DFS over reduced Latin squares of order n (first row and column 0..n-1)."""
    L = [[-1] * n for _ in range(n)]
    L[0] = list(range(n))
    for i in range(n):
        L[i][0] = i
    colused = [set([L[i][c] for i in range(n) if L[i][c] >= 0]) for c in range(n)]
    def rec(i, c):
        if i == n:
            yield [row[:] for row in L]; return
        if c == n:
            yield from rec(i + 1, 1); return
        rowused = set(L[i][:c])
        for s in range(n):
            if s in rowused or s in colused[c]:
                continue
            L[i][c] = s; colused[c].add(s)
            yield from rec(i, c + 1)
            colused[c].discard(s); L[i][c] = -1
    yield from rec(1, 1)


def main():
    mode, n = sys.argv[1], int(sys.argv[2])
    from collections import Counter
    cnt = Counter(); total = 0
    squares = reduced_squares(n) if mode == 'exact' else read_squares(n, sys.stdin.buffer)
    for L in squares:
        total += 1
        cnt[classify(L)] += 1
    print(f'n={n} mode={mode} squares={total}')
    for k, v in sorted(cnt.items(), key=lambda kv: -kv[1]):
        print(f'  {k}: {v}  ({v/total:.4f})')


if __name__ == '__main__':
    main()
